permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  network_key:
    - 157
    - 113
    - 98
    - 36
    - 240
    - 227
    - 195
    - 191
    - 50
    - 219
    - 183
    - 45
    - 113
    - 255
    - 172
    - 35
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x00158d0009ee8244':
    friendly_name: Temperature Sensor
  '0x00158d0009df2763':
    friendly_name: '0x00158d0009df2763'
